# Generated by Django 3.1.7 on 2021-04-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_booking_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advisorid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
